{% set name = "MEAutility" %}
{% set version = "1.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4595e9fc73d4af43bd9819f173f448ad1aa7cacda0a98953045866ec5a9fc89

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base
    - numpy
    - python
    - pyyaml

test:
  requires:
    - pytest
  imports:
    - MEAutility
    - MEAutility.tests
  commands:
    - py.test -vsx --pyargs MEAutility

about:
  home: https://github.com/alejoe91/MEAutility
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: Python package for multi-electrode array (MEA) handling and stimulation.
  doc_url: https://meautility.readthedocs.io/en/latest/
  dev_url: https://github.com/alejoe91/MEAutility

extra:
  recipe-maintainers:
    - alejoe91
